name: Update Parent Issues on Comment

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: read
  contents: read

jobs:
  update-parent-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

      - name: Update Parent Issues
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}

          # Fetch the issue description
          DESCRIPTION=$(gh issue view $ISSUE_NUMBER --json body -q .body)

          # Find the "Parents" line in the description
          PARENTS_LINE=$(echo "$DESCRIPTION" | grep -oP 'Parents:\s*#[0-9, ]+')
          if [ -z "$PARENTS_LINE" ]; then
            echo "No Parents found, exiting."
            exit 0
          fi

          # Extract parent issue numbers
          PARENT_IDS=$(echo "$PARENTS_LINE" | grep -oP '#\d+' | grep -oP '\d+')

          # Loop through each parent and update its description
          for PARENT_ID in $PARENT_IDS; do
            # Get top 5 busiest child issues
            CHILD_ISSUES=$(gh issue list --repo $REPO --search "Parents: #$PARENT_ID" --json number,comments,title,url --jq 'sort_by(.comments) | reverse | .[:5]')
            TOP_ISSUES=$(echo "$CHILD_ISSUES" | jq -r '.[] | "- [#" + (.number|tostring) + "](" + .url + ") - " + .title + " (" + (.comments|tostring) + " comments)"')

            # Fetch the current description of the parent issue
            PARENT_DESCRIPTION=$(gh issue view $PARENT_ID --json body --jq '.body')

            # Check if delimiters exist
            if echo "$PARENT_DESCRIPTION" | grep -q "<!-- TOP_5_CHILD_ISSUES_START -->"; then
              # Replace existing block between delimiters
              UPDATED_DESCRIPTION=$(echo "$PARENT_DESCRIPTION" | sed -e "/<!-- TOP_5_CHILD_ISSUES_START -->/,/<!-- TOP_5_CHILD_ISSUES_END -->/c\\<!-- TOP_5_CHILD_ISSUES_START -->\n$TOP_ISSUES\n<!-- TOP_5_CHILD_ISSUES_END -->")
            else
              # Append new block if delimiters do not exist
              UPDATED_DESCRIPTION="$PARENT_DESCRIPTION\n\n<!-- TOP_5_CHILD_ISSUES_START -->\n$TOP_ISSUES\n<!-- TOP_5_CHILD_ISSUES_END -->"
            fi

            # Update the parent issue description
            gh issue edit $PARENT_ID --body "$UPDATED_DESCRIPTION"
          done
     

